### ISSUE TITLE
[2.0] Checklist

### ISSUE THREAD

**Issue by brettsmason** [brettsmason/croft#7]
This will be an ongoing list of 2.0 changes as and when I think of them.

- [ ] Remove `hybrid_attr` system and replace with JSON-P?
- [ ] Check Gulp build system is working correctly
- [ ] Social media customizer control (sortable?) to replace menu system
- [ ] Move to flexbox
- [ ] Finish integrating new Sass structure
- [ ] Decide on a menu system and implement it!
- [ ] Clean up Sass as much as possible and make less opinionated
- [ ] Add cache busting to stop caching issues of old stylesheets
- [ ] Add additional custom customizer controls (sortable text inputs, gallery etc?)
